### ISSUE TITLE
Collection.IsLockedAsync() returns true for unlocked collection

### ISSUE THREAD

**Issue by fsobolev** [Ace4896/DBus.Services.Secrets#1]
Hello! Thanks for this very nice package! It's useful, but unfortunately I encountered some bugs so I'm going to open issues for everything I found :)
First is that `Collection.IsLockedAsync()` always returns true, even when the collection is unlocked.

```csharp
using DBus.Services.Secrets;
using System;

var service = await SecretService.ConnectAsync(EncryptionType.Dh);
var collection = await service.GetDefaultCollectionAsync();
collection.UnlockAsync();

Console.WriteLine(await collection.IsLockedAsync());
```

**Comment by Ace4896** [comment]
Hey, thanks for giving my package a try!

Admittedly, I didn't try getting/setting any D-Bus properties when I first wrote this, since I only added wrapper code to expose the source generated methods and assumed they were working...

I've taken a closer look at each issue you've opened and they seem to be bugs in the source generator, as I was able to replicate each of them [here](https://github.com/Ace4896/SecretsTest) using the raw wrapper classes. Interestingly enough, the source generated code works fine when all properties are read at once, so it could be used as a temporary workaround.

**Comment by Ace4896** [comment]
I've opened https://github.com/affederaffe/Tmds.DBus.SourceGenerator/issues/3 to hopefully narrow down what the root cause is.

**Comment by fsobolev** [comment]
Thanks! I didn't expect all the problems to have the same root cause, sorry for opening 4 separate issues when it could be just one 😅

**Comment by Ace4896** [comment]
I've updated the source generator in 1.2.0 and reading properties appears to work now - do you mind giving this another try?

**Comment by fsobolev** [comment]
> I've updated the source generator in 1.2.0 and reading properties appears to work now - do you mind giving this another try?

This particular issue wasn't fixed, I still get `true` for unlocked kering. But all other issues were fixed.

**EDIT**: ah, hm, I'm sure the keyring was unlocked and it was reported as locked, but  after locking and unlocking it again now the state is reported correctly, and I can't reproduce the bug. And then I noticed that I had similar thing in Seahorse a couple of times: it was showing unlocked keyring as locked, so I guess it's the problem not with the package, so I'm closing the issue. Thanks! 😊
